-- v1: 익명 게시판. 추가형만(DROP·RENAME·MODIFY 금지). MySQL 8.4.
CREATE TABLE IF NOT EXISTS post (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
